version: '2'

volumes:
  jenkins_home:
    external: true

services:
  jenkins:
    image: yinghuiwang/docker-jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
